In [2]:
# 1.	Write a Python Program to Add Two Matrices?

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a+b)

[[ 8 10 12]
 [14 16 18]]


In [3]:
# 2.	Write a Python Program to Multiply Two Matrices?

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a*b)


[[ 7 16 27]
 [40 55 72]]


In [4]:
# 3.	Write a Python Program to Transpose a Matrix?

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.T)


[[1 4]
 [2 5]
 [3 6]]


In [6]:
# 4.	Write a Python Program to Sort Words in Alphabetic Order?

a = input("Enter a string: ")
a = a.split()
a.sort()
print(a)

['ganesh', 'lokesh', 'sai', 'venkata']


In [7]:
# 5.	Write a Python Program to Remove Punctuation From a String?
 
a = input("Enter a string: ")
b = "!@#$%^&*()_+{}|:<>?/.,;'[]\=-"
for i in a:
    if i in b:
        a = a.replace(i,"")
print(a)

password123
